<script lang="ts">
    import type { ParsedComponent, ForwardedEvent, DispatchedEvent } from "./ParsedComponent";
    
    import { InfoBar, Button } from "$lib";

    // TODO: typedefs?
    export let data: ParsedComponent;

    console.log(data);

    const forwardedEvents = <ForwardedEvent[]>data.events.filter(e => e.type === "forwarded");
    const dispatchedEvents = <DispatchedEvent[]>data.events.filter(e => e.type === "dispatched");
</script>

API docs automatically generated by <a href="https://github.com/carbon-design-system/sveld/" target="_blank" rel="noreffer noopener">sveld</a> and <a href="https://github.com/mattjennings/vite-plugin-sveld/" target="_blank" rel="noreffer noopener">vite-plugin-sveld</a>.

<h3>Props</h3>
{#if data.props.length > 0}
    <table>
        <thead>
            <tr><th>Name</th><th>Type</th><th>Default</th><th>Description</th></tr>
        </thead>
        <tbody>
            {#each data.props as { name, type, value, description }}
                <tr>
                    <td>
                        <code>{name ?? "Unknown"}</code>
                    </td>
                    <td>
                        <code>{type ?? "Unknown"}</code>
                    </td>
                    <td>
                        <code>{value ?? "Unknown"}</code>
                    </td>
                    <td>{description ?? "None"}</td>
                </tr>
            {/each}
        </tbody>
    </table>
    {:else}
    None
{/if}

{#if data.rest_props}
    <InfoBar
        severity="information"
        title="This component uses $$restProps."
    >
        All unused props will be passed through to the underlying {@html
            data.rest_props.name.includes(" | ") ?
                new Intl.ListFormat({ style: 'short' }).format(data.rest_props.name.split(" | ").map(name => `<code>${name}</code>`))
                : `<code>${data.rest_props.name}</code>`
        } {data.rest_props.type.toLowerCase()}s as regular attributes.
        <Button slot="action" variant="accent" href="https://svelte.dev/docs#template-syntax-attributes-and-props">More Info</Button>
    </InfoBar>
{/if}

<h3>Slots</h3>
{#if data.slots.length > 0}
    <table>
        <thead>
            <tr><th>Name</th><th>Slot Props</th></tr>
        </thead>
        <tbody>
            {#each data.slots as { name, slot_props }}
                <tr>
                    <td>
                        {@html `<code>${name}</code>` ?? "Unknown"}
                    </td>
                    <td>
                        {#if Object.keys(slot_props).length > 0}
                            <code>{slot_props}</code>
                            {:else}
                            None
                        {/if}
                    </td>
                </tr>
            {/each}
        </tbody>
    </table>
    {:else}
    None
{/if}

<h3>Events</h3>

<h4>Forwarded Events</h4>
{#if forwardedEvents.length > 0}
    {#each forwardedEvents as { name }}
        {@html `<code>${name}</code> `}
    {/each}
    {:else}
    None
{/if}

<h4>Dispatched Events</h4>
{#if dispatchedEvents.length > 0}
    <table>
        <thead>
            <tr><th>Name</th><th>Detail</th></tr>
        </thead>
        <tbody>
            {#each dispatchedEvents as { name, detail }}
                <tr>
                    <td>
                        {@html `<code>${name}</code>` ?? "Unknown"}
                    </td>
                    <td>
                        {@html `<code>${detail}</code>` ?? "None"}
                    </td>
                </tr>
            {/each}
        </tbody>
    </table>
    {:else}
    None
{/if}