<script lang="ts">
	import type { ParsedComponent, ForwardedEvent, DispatchedEvent } from "./ParsedComponent";

	import { InfoBar, Button } from "$lib";

	export let data: ParsedComponent;
	export let manualForward = false;

	const forwardedEvents = <ForwardedEvent[]>data.events.filter(e => e.type === "forwarded");
	const dispatchedEvents = <DispatchedEvent[]>data.events.filter(e => e.type === "dispatched");
</script>

API docs automatically generated by <a
	href="https://github.com/carbon-design-system/sveld/"
	target="_blank"
	rel="noreffer noopener">sveld</a
>
and
<a href="https://github.com/mattjennings/vite-plugin-sveld/" target="_blank" rel="noreffer noopener"
	>vite-plugin-sveld</a
>.

<h3 id="props">Props</h3>
{#if data.props.length > 0}
	<table>
		<thead>
			<tr><th>Name</th><th>Type</th><th>Default</th><th>Description</th></tr>
		</thead>
		<tbody>
			{#each data.props as { name, type, value, description }}
				{#if !name.startsWith("__")}
					<tr>
						<td>
							{#if typeof name !== "undefined"}
								<code>{name}</code>
							{:else}
								Unknown
							{/if}
						</td>
						<td>
							{#if typeof type !== "undefined"}
								<code>{type}</code>
							{:else}
								<code>any</code>
							{/if}
						</td>
						<td>
							<code>{value ?? "undefined"}</code>
						</td>
						<td>{description ?? "None"}</td>
					</tr>
				{/if}
			{/each}
		</tbody>
	</table>
{:else}
	None
{/if}

{#if data.rest_props}
	<InfoBar severity="information" title="This component uses $$restProps.">
		All unused props will be passed through to the underlying {@html data.rest_props.name.includes(
			" | "
		)
			? new Intl.ListFormat({ style: "short" }).format(
					data.rest_props.name.split(" | ").map(name => `<code>${name}</code>`)
			  )
			: `<code>${data.rest_props.name}</code>`}
		{data.rest_props.type.toLowerCase()}{data.rest_props.name.includes(" | ") ? "s" : ""} as regular
		attributes.
		<Button
			slot="action"
			variant="accent"
			href="https://svelte.dev/docs#template-syntax-attributes-and-props">More Info</Button
		>
	</InfoBar>
{/if}

<h3 id="slots">Slots</h3>
{#if data.slots.length > 0}
	<table>
		<thead>
			<tr><th>Name</th><th>Slot Props</th><th>Fallback</th></tr>
		</thead>
		<tbody>
			{#each data.slots as { name, slot_props, fallback }}
				<tr>
					<td>
						{#if typeof name !== "undefined"}
							<code>{name === "__default__" ? "Unnamed (Default)" : name}</code>
						{:else}
							Unknown
						{/if}
					</td>
					<td>
						{#if slot_props}
							<code>{slot_props}</code>
						{:else}
							None
						{/if}
					</td>
					<td>
						{#if typeof fallback !== "undefined"}
							<code>{fallback.substr(0, 300)}</code>{fallback.length > 300 ? "…" : ""}
						{:else}
							Empty
						{/if}
					</td>
				</tr>
			{/each}
		</tbody>
	</table>
{:else}
	None
{/if}

<h3 id="events">Events</h3>
{#if manualForward}
	<h4>Forwarded Events</h4>
	{#if forwardedEvents.length > 0}
		{#each forwardedEvents as { name }}
			<code class="forwarded">
				<a
					href="https://developer.mozilla.org/en-US/docs/Web/API/Element/{name}_event"
					target="_blank"
					rel="noreferrer noopener">{name.trim()}</a
				>
			</code>
		{/each}
	{:else}
		None
	{/if}
{:else}
	<p>
		All DOM events are forwarded to this component's respective elements by default. <a
			href="#todo">Learn More</a
		>
	</p>
{/if}

<h4>Dispatched Events</h4>
{#if dispatchedEvents.length > 0}
	<table>
		<thead>
			<tr><th>Name</th><th>Detail</th></tr>
		</thead>
		<tbody>
			{#each dispatchedEvents as { name, detail }}
				<tr>
					<td>
						{#if typeof name !== "undefined"}
							<code>{name}</code>
						{:else}
							Unknown
						{/if}
					</td>
					<td>
						{#if typeof detail !== "undefined"}
							<code>{detail}</code>
						{:else}
							None
						{/if}
					</td>
				</tr>
			{/each}
		</tbody>
	</table>
{:else}
	<p>None</p>
{/if}

<style>
	.forwarded {
		display: inline-flex;
		margin-inline-end: 4px;
		margin-block-end: 4px;
	}
</style>
