<script lang="ts">
	import type { DispatchedEvent, ForwardedEvent, ParsedComponent } from "./ParserComponent"
	import { external } from "$site/lib"
	import { Button, InfoBar } from "$lib"
	// import { preprocess } from "svelte/compiler";
	// import sveltePreprocess from "svelte-preprocess";

	export let component: string
	let data: ParsedComponent

	let forwardedEvents: ForwardedEvent[]
	let dispatchedEvents: DispatchedEvent[]

	/*onMount(async () => {
		let raw: string = await import(`src/lib/${ component }/${ component }.svelte?raw`);
		let id = `${ component }.svelte`;

		let { code } = await preprocess(raw, sveltePreprocess(), {
			filename: id
		});

		data = new ComponentParser({
			verbose: false
		}).parseSvelteComponent(code, {
			filePath: id,
			moduleName: id
		});

		forwardedEvents = <ForwardedEvent[]>data.events.filter(e => e.type === "forwarded");
		dispatchedEvents = <DispatchedEvent[]>data.events.filter(e => e.type === "dispatched");
	})*/
</script>

API docs automatically generated by <a {...external} href="https://github.com/carbon-design-system/sveld/">sveld</a>
and <a {...external} href="https://github.com/mattjennings/vite-plugin-sveld/">vite-plugin-sveld</a>.

<h3>Props</h3>
{#if data.props.length > 0}
	<table>
		<thead>
		<tr>
			<th>Name</th>
			<th>Type</th>
			<th>Default</th>
			<th>Description</th>
		</tr>
		</thead>
		<tbody>
		{#each data.props as {name, type, value, description}}
			<tr>
				<td>
					<code>{name ?? "Unknown"}</code>
				</td>
				<td>
					<code>{type ?? "Unknown"}</code>
				</td>
				<td>
					<code>{value ?? "Unknown"}</code>
				</td>
				<td>{description ?? "None"}</td>
			</tr>
		{/each}
		</tbody>
	</table>
{:else}
	None
{/if}

{#if data.rest_props}
	<InfoBar severity="information" title="This component uses $$restProps.">
		All unused props will be passed through to the underlying {@html
	  data.rest_props.name.includes(" | ")
		  ? new Intl.ListFormat({style: "short"}).format(data.rest_props.name
			  .split(" | ")
			  .map(name => `<code>${name}</code>`
			  ))
		  : `<code>${data.rest_props.name}</code>`
	} {data.rest_props.type.toLowerCase()}s as regular attributes.

		<Button
				slot="action"
				variant="accent"
				href="https://svelte.dev/docs#template-syntax-attributes-and-props"
				{...external}
		>
			More Info
		</Button>
	</InfoBar>
{/if}

<h3>Slots</h3>
{#if data.slots.length > 0}
	<table>
		<thead>
		<tr>
			<th>Name</th>
			<th>Slot Props</th>
			<th>Fallback</th>
		</tr>
		</thead>
		<tbody>
		{#each data.slots as {name, slot_props, fallback}}
			<tr>
				<td>{@html name ? `<code>${name}</code>` : "Unknown"}</td>
				<td>{@html Object.keys(JSON.parse(slot_props)).length > 0 ? `<code>${slot_props}</code>` : "None"}</td>
				<td>{@html fallback ? `<code>${fallback}</code>` : "None"}</td>
			</tr>
		{/each}
		</tbody>
	</table>
{:else}
	None
{/if}

<h3>Events</h3>

<h4>Forwarded Events</h4>
{#if forwardedEvents.length > 0}
	{#each forwardedEvents as { name }}
		<code class="forwarded">
			<a href="https://developer.mozilla.org/en-US/docs/Web/API/Element/{name}_event" {...external}>
				{name.trim()}
			</a>
		</code>
	{/each}
{:else}
	None
{/if}

<h4>Dispatched Events</h4>
{#if dispatchedEvents.length > 0}
	<table>
		<thead>
		<tr>
			<th>Name</th>
			<th>Detail</th>
		</tr>
		</thead>
		<tbody>
		{#each dispatchedEvents as {name, detail}}
			<tr>
				<td>{@html name ? `<code>${name}</code>` : "Unknown"}</td>
				<td>{@html detail ? `<code>${detail}</code>` : "None"}</td>
			</tr>
		{/each}
		</tbody>
	</table>
{:else}
	None
{/if}

<style>
	.forwarded {
		display: inline-flex;
		margin-inline-end: 4px;
		margin-block-end: 4px;
	}
</style>